import { Body, Controller, Delete, Get, Param, ParseUUIDPipe, Patch, Post, Query } from '@nestjs/common';
import { ApiBody, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags } from '@nestjs/swagger';
import { ZodValidationPipe } from 'nestjs-zod';

import { Auth } from '../../auth/decorators/auth.decorator';
import { CurrentUser } from '../../auth/decorators/current-user.decorator';
import type { RequestUser } from '../../auth/interfaces/authenticated-user.interface';
import { ApiDataResponse } from '../../common/decorators/api-data-response.decorator';
import { PERMISSIONS } from '../../common/constants/roles.constants';
import {
  attributeDefListQuerySchema,
  CreateAttributeDefBodyDto,
  createAttributeDefSchema,
  GraphAttributeDefDto,
  GraphAttributeDefListDto,
  PatchAttributeDefBodyDto,
  patchAttributeDefSchema,
  type AttributeDefListQuery,
  type CreateAttributeDefDto,
  type GraphAttributeDefResponse,
  type PatchAttributeDefDto,
} from '../dto/graph-attribute-def.dto';
import { GraphAttributeDefsService, MAX_LIVE_ATTRIBUTE_DEFS_PER_TYPE } from './graph-attribute-defs.service';

// =============================================================================
// GraphAttributeDefsController (#355, epic #344; docs/specs/ontology.md §17.3)
// =============================================================================
//
// `/api/graph/attribute-defs` — your own attributes on the ontology's types.
// A definition shows up in `GET /api/graph/ontology` with `source: 'user'`.
// Owner-only: another user's definition is a 404, never a 403.
// =============================================================================

@ApiTags('Graph')
@Controller('graph/attribute-defs')
export class GraphAttributeDefsController {
  constructor(private readonly defs: GraphAttributeDefsService) {}

  @Get()
  @Auth({ permissions: [PERMISSIONS.GRAPH_READ] })
  @ApiOperation({
    summary: 'List your attribute definitions',
    description:
      'Your own attribute definitions, ordered by entity type, sort order and creation time. ' +
      'Deprecated ones are left out unless `includeDeprecated=true`.',
  })
  @ApiQuery({ name: 'entityType', required: false, type: String, description: 'Only definitions on this entity type' })
  @ApiQuery({ name: 'includeDeprecated', required: false, enum: ['true', 'false'], description: 'Include deprecated definitions (default false)' })
  @ApiDataResponse(GraphAttributeDefListDto, { description: 'Your attribute definitions' })
  async list(
    @Query(new ZodValidationPipe(attributeDefListQuerySchema)) query: AttributeDefListQuery,
    @CurrentUser() user: RequestUser,
  ): Promise<{ items: GraphAttributeDefResponse[] }> {
    return this.defs.list(user.id, query);
  }

  @Post()
  @Auth({ permissions: [PERMISSIONS.GRAPH_WRITE] })
  @ApiOperation({
    summary: 'Define an attribute',
    description:
      'Add your own attribute to an entity type of your effective ontology.\n\n' +
      'The **key is generated by the server** — `u_` plus ten lowercase alphanumerics — and is ' +
      'permanent: values are stored under it, so the label stays renameable. `kind` and ' +
      '`entityType` are fixed once created.\n\n' +
      '- `select`/`multi_select` need `options.choices` (unique values);\n' +
      '- `entity_ref` needs `options.targetTypes`, each an entity type in your graph;\n' +
      '- no other kind takes `options`;\n' +
      '- `extractable: true` needs an `extractionHint` — it is what the model is asked.\n\n' +
      `At most ${MAX_LIVE_ATTRIBUTE_DEFS_PER_TYPE} live definitions per entity type.`,
  })
  @ApiBody({ type: CreateAttributeDefBodyDto })
  @ApiDataResponse(GraphAttributeDefDto, { status: 201, description: 'The new definition' })
  @ApiResponse({
    status: 400,
    description: 'Unknown entity type, invalid options for the kind, a missing extraction hint, or the per-type limit',
  })
  async create(
    @Body(new ZodValidationPipe(createAttributeDefSchema)) dto: CreateAttributeDefDto,
    @CurrentUser() user: RequestUser,
  ): Promise<GraphAttributeDefResponse> {
    return this.defs.create(dto, user);
  }

  @Patch(':id')
  @Auth({ permissions: [PERMISSIONS.GRAPH_WRITE] })
  @ApiOperation({
    summary: 'Change an attribute definition',
    description:
      'Relabel, reorder, change the extraction settings or sensitivity, or add choices. ' +
      '**Choices can be added or relabelled but never removed** — stored values would lose ' +
      'their label (the 400 names the removed values in `details.removedChoices`). ' +
      '`kind`, `entityType` and `key` are immutable. `deprecated: true` retires the ' +
      'definition (values are kept and stay readable); `false` restores it.',
  })
  @ApiParam({ name: 'id', type: String, format: 'uuid' })
  @ApiBody({ type: PatchAttributeDefBodyDto })
  @ApiDataResponse(GraphAttributeDefDto, { description: 'The updated definition' })
  @ApiResponse({ status: 400, description: 'An immutable field sent, a removed choice, or invalid options' })
  @ApiResponse({ status: 404, description: 'No such definition, or not yours' })
  async update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body(new ZodValidationPipe(patchAttributeDefSchema)) dto: PatchAttributeDefDto,
    @CurrentUser() user: RequestUser,
  ): Promise<GraphAttributeDefResponse> {
    return this.defs.update(id, dto, user);
  }

  @Delete(':id')
  @Auth({ permissions: [PERMISSIONS.GRAPH_WRITE] })
  @ApiOperation({
    summary: 'Deprecate an attribute definition',
    description:
      '**Deprecates — never deletes.** Stored values keep their key and stay readable; the ' +
      'attribute leaves forms and extraction. Idempotent: deprecating twice returns the same ' +
      'definition. Restore it with `PATCH … { "deprecated": false }`.',
  })
  @ApiParam({ name: 'id', type: String, format: 'uuid' })
  @ApiDataResponse(GraphAttributeDefDto, { description: 'The definition, with `deprecatedAt` set' })
  @ApiResponse({ status: 404, description: 'No such definition, or not yours' })
  async deprecate(
    @Param('id', ParseUUIDPipe) id: string,
    @CurrentUser() user: RequestUser,
  ): Promise<GraphAttributeDefResponse> {
    return this.defs.deprecate(id, user);
  }
}
