// =============================================================================
// Document fixtures for `note.source.extract` (issue #51, epic #45)
// =============================================================================
//
// BUILT AT TEST TIME RATHER THAN COMMITTED AS BINARY BLOBS, and the choice is
// deliberate: a committed PDF is an opaque file nobody can review in a diff, so
// "the scanned fixture really has no text layer" and "the encrypted fixture is
// really encrypted" become claims a reader has to take on trust. Here they are
// claims the code states — `pdfkit` (already a dependency, for #28's transcript
// export) writes the PDFs, and what each one contains is visible in twenty
// lines.
//
// ⚠ THE SCANNED FIXTURE IS A REAL PDF WITH A REAL IMAGE AND NO TEXT OPERATORS.
// The issue requires exactly that, and the reason is that the scanned case is
// the one the extractor cannot detect by catching an exception: pdf.js parses
// such a file perfectly and returns an empty string. A fixture that was merely
// an empty PDF would pass the same assertion while testing a different thing —
// it would never prove the "pages and images but no text" path works at all.
// So the PNG below is generated byte by byte (no image dependency exists in
// this repository, and adding one for a test would be worse than 30 lines of
// zlib), embedded with `doc.image()`, and nothing writes a single glyph.
// =============================================================================

import PDFDocument from 'pdfkit';
import { deflateSync } from 'node:zlib';

/** Collect a `pdfkit` document into one buffer. */
function render(doc: PDFKit.PDFDocument): Promise<Buffer> {
  const chunks: Buffer[] = [];

  return new Promise((resolve, reject) => {
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

// -----------------------------------------------------------------------------
// A minimal PNG, written by hand
// -----------------------------------------------------------------------------

function crc32(buffer: Buffer): number {
  const table: number[] = [];

  for (let n = 0; n < 256; n += 1) {
    let c = n;

    for (let k = 0; k < 8; k += 1) {
      c = (c & 1) !== 0 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }

    table[n] = c >>> 0;
  }

  let crc = 0xffffffff;

  for (const byte of buffer) {
    crc = (table[(crc ^ byte) & 0xff] as number) ^ (crc >>> 8);
  }

  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);

  const typed = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typed));

  return Buffer.concat([length, typed, crc]);
}

/** A tiny truecolour PNG with a visible gradient — an image, and nothing else. */
export function tinyPng(width = 48, height = 32): Buffer {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour

  const stride = 1 + width * 3;
  const raw = Buffer.alloc(height * stride);

  for (let y = 0; y < height; y += 1) {
    raw[y * stride] = 0; // filter: none

    for (let x = 0; x < width; x += 1) {
      const offset = y * stride + 1 + x * 3;
      raw[offset] = (x * 5) % 256;
      raw[offset + 1] = (y * 7) % 256;
      raw[offset + 2] = 160;
    }
  }

  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw)),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

// -----------------------------------------------------------------------------
// The PDFs
// -----------------------------------------------------------------------------

/** The text the multi-page fixture puts on page one. */
export const PDF_PAGE_ONE = 'Kestrel launch proposal, prepared for the steering group.';

/** The text the multi-page fixture puts on page two. */
export const PDF_PAGE_TWO = 'Budget: the second page states a figure the first one does not.';

/** The text the multi-page fixture puts on page three. */
export const PDF_PAGE_THREE = 'Signatures and appendices follow on the third page.';

/** A three-page PDF with a real text layer. */
export function multiPagePdf(): Promise<Buffer> {
  const doc = new PDFDocument({ autoFirstPage: true });

  doc.fontSize(14).text(PDF_PAGE_ONE);
  doc.addPage().fontSize(14).text(PDF_PAGE_TWO);
  doc.addPage().fontSize(14).text(PDF_PAGE_THREE);

  return render(doc);
}

/** A password-protected PDF. Its text is real and completely unreachable. */
export function encryptedPdf(): Promise<Buffer> {
  const doc = new PDFDocument({
    userPassword: 'open-sesame',
    ownerPassword: 'owner-only',
  });

  doc.fontSize(14).text('Confidential: this text is behind a password.');

  return render(doc);
}

/**
 * A PDF with pages and an image and NOT ONE TEXT OPERATOR — a scan.
 *
 * See the file header for why this has to be a real image rather than an empty
 * page: the extractor's scanned-PDF branch is the one that fires on a
 * SUCCESSFUL parse, so the fixture has to be a document that parses.
 */
export function scannedPdf(): Promise<Buffer> {
  const doc = new PDFDocument({ autoFirstPage: true });

  doc.image(tinyPng(), 40, 40, { width: 400 });
  doc.addPage().image(tinyPng(), 40, 40, { width: 400 });

  return render(doc);
}

/** Bytes that are not a PDF at all. */
export function corruptPdf(): Buffer {
  return Buffer.from('%PDF-1.7\nthis file stops making sense right about here\n');
}

// -----------------------------------------------------------------------------
// The text fixtures
// -----------------------------------------------------------------------------

/** UTF-8 byte order mark: what Notepad and a great deal of Windows tooling write. */
export const UTF8_BOM = Buffer.from([0xef, 0xbb, 0xbf]);

/** The text inside `bomTextFile`, without its BOM. */
export const BOM_TEXT_BODY = 'Briefing notes — prepared 14 September.\nSecond line.';

/** A UTF-8 text file that begins with a byte order mark. */
export function bomTextFile(): Buffer {
  return Buffer.concat([UTF8_BOM, Buffer.from(BOM_TEXT_BODY, 'utf8')]);
}

/**
 * A Markdown file with a fenced code block, whose fences must survive intact.
 *
 * The fence matters more than it looks: the model reads Markdown natively, and
 * an extractor that "cleaned up" the document would destroy the one signal that
 * says "this block is code, not prose".
 */
export const MARKDOWN_BODY = [
  '# Deployment brief',
  '',
  'Run the migration first:',
  '',
  '```bash',
  'npm run prisma:migrate',
  '```',
  '',
  '> Then restart the API.',
  '',
  '| Step | Owner |',
  '| ---- | ----- |',
  '| 1    | Ana   |',
  '',
].join('\n');

/** A Markdown file. */
export function markdownFile(): Buffer {
  return Buffer.from(MARKDOWN_BODY, 'utf8');
}
