import {
  buildNoteExportDocument,
  formatDate,
  formatSource,
  noteExportFilename,
  provenanceEntries,
} from './note-export-document';
import { noteDocument } from './__fixtures__/note-document';

// =============================================================================
// The note export document and its provenance block (issue #54, §8.2 / §8.3)
// =============================================================================
//
// This file is the ONE definition of what every format's header says, so the
// assertions here are the assertions all three renderers inherit.
// =============================================================================

describe('provenanceEntries', () => {
  it('always names the source, the template, the version and the export time', () => {
    // Issue #54's acceptance criterion, stated as a property of the block
    // rather than of any one renderer.
    const labels = provenanceEntries(noteDocument()).map((entry) => entry.label);

    expect(labels.slice(0, 4)).toEqual(['Source', 'Template', 'Note version', 'Exported']);
  });

  it('says `None` for a note written without a template', () => {
    // Not a dropped line: "this note used no template" is information, and a
    // missing line is indistinguishable from a renderer that forgot.
    const entries = provenanceEntries(noteDocument({ templateName: null }));

    expect(entries.find((entry) => entry.label === 'Template')?.value).toBe('None');
  });

  it('names the model that generated the note, when one did', () => {
    const entries = provenanceEntries(noteDocument());

    expect(entries.find((entry) => entry.label === 'Generated by')?.value).toBe('openai · gpt-4o');
  });

  it('omits the AI and author lines when there is genuinely nothing to say', () => {
    // A hand-written note has no model; the AI's own version has no human
    // author. An omitted line beats a printed dash for both.
    const labels = provenanceEntries(
      noteDocument({ provider: null, author: null }),
    ).map((entry) => entry.label);

    expect(labels).toEqual(['Source', 'Template', 'Note version', 'Exported']);
  });

  it('carries the export timestamp as ISO-8601, not a locale string', () => {
    const entries = provenanceEntries(noteDocument());

    expect(entries.find((entry) => entry.label === 'Exported')?.value).toBe(
      '2026-09-14T04:37:11.000Z',
    );
  });
});

describe('formatSource', () => {
  it('names the title, the date and the kind', () => {
    expect(
      formatSource({
        type: 'transcript',
        id: 't1',
        title: 'Weekly Sync',
        date: new Date('2026-09-12T09:00:00Z'),
      }),
    ).toBe('Weekly Sync — Sep 12, 2026 (transcript)');
  });

  it('drops the date rather than inventing one', () => {
    // A provenance line that guessed would be worse than one that omits: the
    // whole point of the block is that a reader can trust what it says.
    expect(formatSource({ type: 'document', id: 'o1', title: 'contract.pdf', date: null })).toBe(
      'contract.pdf (document)',
    );
  });

  it('names the kind even for a note source', () => {
    // "Generated from another note" is a materially different provenance claim
    // from "generated from a recording", and a reader outside this application
    // has no other way to tell them apart.
    expect(formatSource({ type: 'note', id: 'n1', title: 'Q3 plan', date: null })).toBe(
      'Q3 plan (note)',
    );
  });
});

describe('formatDate', () => {
  it('is UTC and locale-independent', () => {
    // Content-addressed reuse hands the SECOND caller the FIRST caller's file,
    // so a date that depended on the renderer's timezone would make two
    // identical requests legitimately disagree about what they contain.
    expect(formatDate(new Date('2026-01-01T23:30:00Z'))).toBe('Jan 1, 2026');
    expect(formatDate(new Date('2026-12-31T00:30:00Z'))).toBe('Dec 31, 2026');
  });
});

describe('noteExportFilename', () => {
  it('is `<title> (v<n>).<ext>`', () => {
    expect(noteExportFilename('Weekly Sync Recap', 3, 'docx')).toBe(
      'Weekly Sync Recap (v3).docx',
    );
  });

  it('replaces the characters a filesystem or a browser would refuse', () => {
    expect(noteExportFilename('Q3: plans/ideas?', 1, 'pdf')).toBe('Q3- plans-ideas- (v1).pdf');
  });

  it('falls back to `note`, never to another document type\'s word', () => {
    // An attachment called `transcript (v3).docx` would be actively misleading
    // about what the reader is opening.
    expect(noteExportFilename('   ', 3, 'md')).toBe('note (v3).md');
  });

  it('bounds the name so the whole filename fits a filesystem', () => {
    expect(noteExportFilename('x'.repeat(400), 2, 'pdf').length).toBeLessThan(140);
  });

  it('keeps non-ASCII, which travels in the header\'s `filename*` parameter', () => {
    expect(noteExportFilename('Café réunion', 1, 'md')).toBe('Café réunion (v1).md');
  });
});

describe('buildNoteExportDocument', () => {
  it('substitutes a placeholder title rather than rendering an empty heading', () => {
    expect(buildNoteExportDocument({ ...noteDocument(), title: '  ' }).title).toBe('Untitled note');
  });

  it('leaves the body exactly as stored', () => {
    const body = '  leading and trailing whitespace matter to markdown  ';

    expect(buildNoteExportDocument({ ...noteDocument(), body }).body).toBe(body);
  });
});
