import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { APP_NAME, THEME_COLOR, BACKGROUND_COLOR } from '@app/shared';
import { buildManifest } from '../../../pwa/manifest';

// =============================================================================
// The web app manifest  (issue #217, epic #215)
// =============================================================================
//
// Two invariants nothing else in the repository enforces:
//
//   1. The manifest DERIVES its branding rather than restating it. A fork
//      renames the product in one line of `@app/shared`; a manifest holding
//      its own copy would ship an installed app whose OS task-switcher label
//      and splash screen still said the old thing, and nobody would notice
//      because the running React app would look correct.
//
//   2. Every icon `src` names a file that actually exists. The icons were
//      committed by a DIFFERENT change (issue #216) and are regenerated by
//      `apps/web/scripts/generate-icons.py`, so a rename there breaks
//      installability here with no build error at all — Vite copies `public/`
//      verbatim and never validates that the manifest's paths resolve. The
//      failure would first appear as a platform silently refusing to install
//      the app, which is the worst place to learn about it.
//
// Assertions are written against the shared constants, not against their
// current values, so rebranding the template keeps this suite green.
// =============================================================================

const webRoot = resolve(__dirname, '..', '..', '..');

describe('buildManifest', () => {
  it('takes its name from the shared APP_NAME constant', () => {
    const manifest = buildManifest();

    expect(manifest.name).toBe(APP_NAME);
    expect(manifest.short_name).toBe(APP_NAME);
  });

  it('declares standalone display, which is what iOS reads to allow installation', () => {
    // Safari grants the Notifications API only to a web app added to the Home
    // Screen, and it only offers that for a manifest requesting standalone.
    // Weakening this field silently removes every iPhone and iPad from the
    // reach of epic #215.
    expect(buildManifest().display).toBe('standalone');
  });

  it('takes its colours from the shared constants', () => {
    const manifest = buildManifest();

    expect(manifest.theme_color).toBe(THEME_COLOR);
    expect(manifest.background_color).toBe(BACKGROUND_COLOR);
  });

  it('scopes the app to the site root and marks installed launches', () => {
    const manifest = buildManifest();

    expect(manifest.id).toBe('/');
    expect(manifest.scope).toBe('/');
    expect(manifest.start_url).toBe('/?source=pwa');
  });

  it('references only icons that exist in public/', () => {
    const icons = buildManifest().icons;
    expect(icons.length).toBeGreaterThan(0);

    const missing = icons
      .map((icon) => icon.src)
      .filter((src) => !existsSync(resolve(webRoot, 'public', src.replace(/^\//, ''))));

    expect(missing, `manifest icons with no file under apps/web/public: ${missing.join(', ')}`)
      .toEqual([]);
  });

  it('offers the icon purposes each install surface needs', () => {
    const purposes = new Set(buildManifest().icons.map((icon) => icon.purpose));

    // `any` is the plain launcher icon, `maskable` is what Android crops into
    // its adaptive-icon shape (an `any`-only manifest gets letterboxed in a
    // white circle), and `monochrome` is the small badge a notification draws
    // in the status bar — the reason epic #215 needs it at all.
    expect(purposes).toEqual(new Set(['any', 'maskable', 'monochrome']));
  });

  it('gives every icon a size and a declared MIME type', () => {
    for (const icon of buildManifest().icons) {
      expect(icon.sizes, `${icon.src} has no sizes`).toMatch(/^\d+x\d+$/);
      expect(icon.type, `${icon.src} has no type`).toBe('image/png');
    }
  });

  it('is serialisable as the JSON the build emits', () => {
    expect(() => JSON.parse(JSON.stringify(buildManifest()))).not.toThrow();
  });
});
