// =============================================================================
// The Ask tool contract (#377, epic #348; docs/specs/ontology.md §9.3, §21)
// =============================================================================
//
// One `AskTool` per fixed, parameterised read shape. §9.3 is absolute: no
// free-form SQL or Cypher is ever generated by a model — a tool's arguments are
// validated by its own Zod schema and reach the database only as bound
// parameters of a read the graph API already has.
//
// `parameters` is the JSON Schema the model sees, in the strict subset
// `assertStrictJsonSchema` enforces (#358/#359): `type: 'object'`,
// `additionalProperties: false`, EVERY property in `required`, optional ones
// spelled `[T, 'null']`, and no bounds keywords — the bounds live in the
// description for the model and in `input` for the server. `input` mirrors it
// and normalises `null` to `undefined`, so a tool reads "not given" one way.
//
// A tool signals a MODEL MISTAKE (an unknown handle, a wrong kind of handle) by
// throwing `AskToolError` with a short, model-readable message; the executor
// turns it into `ok: false`. Anything else a tool throws is a bug.
// =============================================================================

import { z } from 'zod';

import type { JsonSchema } from '../../ai/providers/ai-provider.interface';
import type { RequestUser } from '../../auth/interfaces/authenticated-user.interface';
import { HANDLE_KIND_NOUNS, handleKindOf, type HandleKind, type HandleRegistry, type HandleTarget } from './handle-registry';

export interface AskToolContext {
  /** The owner — every query is scoped to `user.id`. */
  user: RequestUser;
  /** This turn's handles. */
  handles: HandleRegistry;
  /**
   * §14 opt-in for `personal` PersonFacts. Always false until a preference
   * exists in #369's `graph` namespace — see `personalFactsAllowedFor`.
   * `sensitive` ones are never returned whatever this says.
   */
  personalFactsAllowed: boolean;
  /** The conversation's scope entity, if any (#376); #378 pre-registers it. */
  scopeEntityId: string | null;
  now: Date;
  /**
   * The resolved model's `countTokens` (#360's `AiModelResolution`), used to
   * hold a result to `ASK_TOOL_RESULT_MAX_TOKENS`. Absent → a conservative
   * character estimate.
   */
  countTokens?: (text: string) => number;
}

export interface AskToolResult {
  /** Handle-based and uuid-free. An array is serialised as `{ items: [...] }`. */
  data: unknown;
  resultCount: number;
  /** One human line for the UI's tool-call list (#376 `askToolCallSchema.summary`). */
  summary: string;
  /** More existed than was returned (by the tool's own limit, or by compaction). */
  truncated: boolean;
}

export interface AskTool<I> {
  name: string;
  description: string;
  parameters: JsonSchema;
  input: z.ZodType<I>;
  run(ctx: AskToolContext, input: I): Promise<AskToolResult>;
}

/** A model mistake the executor reports as `ok: false`. The message is shown to the model. */
export class AskToolError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'AskToolError';
  }
}

// -----------------------------------------------------------------------------
// Handles
// -----------------------------------------------------------------------------

/**
 * Resolve a handle the model passed, accepting only `kinds`. Throws
 * `AskToolError` for anything else, naming what went wrong.
 */
export function resolveHandleOrThrow(ctx: AskToolContext, raw: string, kinds: readonly HandleKind[]): HandleTarget {
  const value = raw.trim();
  const expected = kinds.map((k) => `${k}N`).join(' or ');
  const kind = handleKindOf(value);
  if (kind === null) {
    throw new AskToolError(
      `"${value.slice(0, 40)}" is not a reference. Pass a reference such as ${kinds[0]}1 from an earlier tool result.`,
    );
  }
  if (!kinds.includes(kind)) {
    throw new AskToolError(
      `${value} is ${articled(HANDLE_KIND_NOUNS[kind])} reference; this parameter takes ${expected}.`,
    );
  }
  const target = ctx.handles.resolve(value);
  if (!target) {
    throw new AskToolError(`Unknown ${HANDLE_KIND_NOUNS[kind]} reference ${value}. Use search first.`);
  }
  return target;
}

function articled(noun: string): string {
  return /^[aeiou]/.test(noun) ? `an ${noun}` : `a ${noun}`;
}

// -----------------------------------------------------------------------------
// Output formatting — every tool shares one date, clip and precision rule
// -----------------------------------------------------------------------------

export const QUOTE_MAX_CHARS = 300;
export const STATEMENT_MAX_CHARS = 400;

/** `YYYY-MM-DD` (UTC), or null. */
export function isoDate(value: Date | string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const d = typeof value === 'string' ? new Date(value) : value;
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
}

/** Whitespace-collapsed and cut to `max` characters, with an ellipsis when cut. */
export function clip(text: string | null | undefined, max: number): string {
  const s = (text ?? '').replace(/\s+/g, ' ').trim();
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

/** `3 entities`, `1 entity`. */
export function plural(n: number, one: string, many: string): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** `{ precision }` only when it says something beyond "to the day". */
export function precisionField(precision: string | null | undefined): { precision?: string } {
  return precision && precision !== 'day' ? { precision } : {};
}

// -----------------------------------------------------------------------------
// Strict-compatible JSON Schema builders (see the header)
// -----------------------------------------------------------------------------

export function objectParameters(properties: Record<string, JsonSchema>): JsonSchema {
  return { type: 'object', additionalProperties: false, properties, required: Object.keys(properties) };
}

export const jsonString = (description: string): JsonSchema => ({ type: 'string', description });
export const jsonNullableString = (description: string): JsonSchema => ({ type: ['string', 'null'], description });
export const jsonNullableInteger = (description: string): JsonSchema => ({ type: ['integer', 'null'], description });
export const jsonNullableEnum = (values: readonly (string | number)[], description: string): JsonSchema => ({
  type: [typeof values[0] === 'number' ? 'integer' : 'string', 'null'],
  enum: [...values, null],
  description,
});
export const jsonNullableStringArray = (description: string): JsonSchema => ({
  type: ['array', 'null'],
  items: { type: 'string' },
  description,
});

// -----------------------------------------------------------------------------
// Zod mirrors: `null` (strict mode's "not given") and absent both → undefined
// -----------------------------------------------------------------------------

export function optionalOf<T extends z.ZodType>(schema: T) {
  return schema
    .nullish()
    .transform((v): z.output<T> | undefined => (v === null || v === undefined ? undefined : (v as z.output<T>)));
}

/** A handle: short, whitespace-trimmed. Resolution happens in the tool. */
export const zHandle = z.string().trim().min(1).max(40);

/** `YYYY-MM-DD` or an ISO 8601 datetime with an offset — the graph read layer's `as_of` grammar. */
export const zDate = z.union([z.iso.date(), z.iso.datetime({ offset: true })]);

/** Bounded list of type/kind keys (validated against the caller's schema downstream). */
export const zKeyList = z.array(z.string().trim().min(1).max(64)).max(32);
