import { expect, test, type Page } from '@playwright/test';
import { harnessUrl, waitForInter } from '../support/harness';
import { installGraphGuideApi, installGraphReviewApi } from '../support/graphApi';
import { installHomeApi } from '../support/homeApi';
import { installNotesApi } from '../support/notesApi';

/**
 * Guide the graph, add to graph from a selection, and Home's "Waiting for
 * review" (issue #368, epic #346).
 *
 * - The extract dialog, re-opened through the review sheet's "Edit guidance"
 *   with the draft's guidance pre-filled and expanded, at 1440 and 390 (full
 *   screen on the phone).
 * - The add-to-graph dialog on a phone, reached from a real text selection in
 *   the rendered note body and the phone's bottom "Add to graph" bar.
 * - The Home card, at 1440.
 *
 * `installGraphGuideApi` is registered LAST so its `/ai/config` (task models),
 * estimate, guided draft and drafts list win; everything else falls back to
 * the notes/home stubs. Baselines are generated by CI's visual-baselines
 * workflow (the pinned Playwright image), never locally.
 */

const PHONE = { width: 390, height: 844 };
const DESKTOP = { width: 1440, height: 900 };

const WIDTHS = [
  ['phone-390', PHONE],
  ['desktop-1440', DESKTOP],
] as const;

/** Select rendered text in the note body the way a reader would, then release. */
async function selectInNote(page: Page, from: string, to: string) {
  await page.evaluate(
    ([fromText, toText]) => {
      const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let start: { node: Node; offset: number } | null = null;
      let end: { node: Node; offset: number } | null = null;
      for (let node = walker.nextNode(); node; node = walker.nextNode()) {
        const text = node.textContent ?? '';
        if (!start && text.includes(fromText)) start = { node, offset: text.indexOf(fromText) };
        if (start && text.includes(toText)) {
          end = { node, offset: text.indexOf(toText) + toText.length };
          break;
        }
      }
      if (!start || !end) throw new Error('Selection text not found');
      const range = document.createRange();
      range.setStart(start.node, start.offset);
      range.setEnd(end.node, end.offset);
      const selection = window.getSelection()!;
      selection.removeAllRanges();
      selection.addRange(range);
      document.dispatchEvent(new PointerEvent('pointerup', { bubbles: true }));
    },
    [from, to] as const,
  );
}

test.describe('Guide the graph', () => {
  for (const [name, viewport] of WIDTHS) {
    test(`extract dialog @ ${name}`, async ({ page }) => {
      await installNotesApi(page);
      await installGraphReviewApi(page);
      await installGraphGuideApi(page);
      await page.setViewportSize(viewport);
      await page.goto(harnessUrl({ route: '/notes/n1?review=1' }));
      await waitForInter(page);

      await expect(page.getByRole('heading', { name: /People/ })).toBeVisible();
      await page.getByRole('button', { name: 'Edit guidance' }).click();

      const dialog = page.getByRole('dialog', { name: 'Extract again' });
      await expect(dialog).toBeVisible();
      await expect(dialog.getByRole('combobox', { name: 'Model' })).toHaveText('GPT-4.1');
      await expect(dialog.getByText('About 6,840 input tokens · 1 request')).toBeVisible();
      await expect(dialog.getByRole('textbox', { name: 'Instructions' })).toHaveValue(/Only the storage migration/);
      await expect(dialog.getByRole('button', { name: 'Ana Ruiz' })).toBeVisible();

      await expect(page).toHaveScreenshot(`graph-guide-extract-${name}.png`);
    });
  }

  test('add-to-graph dialog @ phone-390', async ({ page }) => {
    await installNotesApi(page);
    await installGraphReviewApi(page);
    await installGraphGuideApi(page);
    await page.setViewportSize(PHONE);
    await page.goto(harnessUrl({ route: '/notes/n1' }));
    await waitForInter(page);

    await expect(page.getByText('behind a flag').first()).toBeVisible();
    await expect(page.getByRole('button', { name: /Graph proposal/ })).toBeVisible();
    await selectInNote(page, 'storage migration', 'behind a flag');

    const bar = page.getByTestId('graph-selection-bar');
    await expect(bar).toBeVisible();
    await bar.getByRole('button', { name: 'Add to graph' }).click();

    const dialog = page.getByRole('dialog', { name: 'Add to graph' });
    await expect(dialog).toBeVisible();
    await expect(dialog.getByRole('textbox', { name: 'Name' })).toHaveValue('storage migration **behind a flag');
    await expect(dialog.getByRole('button', { name: 'Add to draft' })).toBeEnabled();

    await expect(page).toHaveScreenshot('graph-guide-add-phone-390.png');
  });

  test('Home "Waiting for review" @ desktop-1440', async ({ page }) => {
    await installHomeApi(page);
    await installGraphGuideApi(page);
    await page.setViewportSize(DESKTOP);
    await page.goto(harnessUrl({ route: '/' }));
    await waitForInter(page);

    await expect(page.getByRole('heading', { name: 'Hi, Visual' })).toBeVisible();
    const section = page.getByRole('region', { name: 'Waiting for review' });
    await expect(section).toBeVisible();
    await expect(section.getByRole('heading', { name: 'Possible duplicates in your graph' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Shared with me', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'New transcript', exact: true })).toBeEnabled();

    await expect(page).toHaveScreenshot('graph-guide-home-desktop-1440.png');
  });
});
