import { expect, test } from '@playwright/test';
import { harnessUrl, waitForInter } from '../support/harness';
import { installGraphReviewApi } from '../support/graphApi';
import { installNotesApi } from '../support/notesApi';

/**
 * The graph proposal review sheet on the note page (issue #367, epic #346):
 * a right-hand drawer beside the note at desktop width, a bottom sheet on a
 * phone, the extracting and committed states, and the row editor — full
 * screen on a phone.
 *
 * `installNotesApi` serves the note; `installGraphReviewApi` is registered
 * AFTER it so its `/ai/config` (graph on) and `/graph/*` answers win, and it
 * falls back to the notes stubs for everything else.
 *
 * Baselines are generated by CI's visual-baselines workflow (the pinned
 * Playwright image), never locally.
 */

const PHONE = { width: 390, height: 844 };
const DESKTOP = { width: 1440, height: 900 };

const WIDTHS = [
  ['phone-390', PHONE],
  ['desktop-1440', DESKTOP],
] as const;

test.describe('Graph proposal review sheet', () => {
  for (const [name, viewport] of WIDTHS) {
    test(`draft proposal @ ${name}`, async ({ page }) => {
      await installNotesApi(page);
      await installGraphReviewApi(page);
      await page.setViewportSize(viewport);
      await page.goto(harnessUrl({ route: '/notes/n1?review=1' }));
      await waitForInter(page);

      await expect(page.getByRole('heading', { name: 'Graph proposal' })).toBeVisible();
      await expect(page.getByRole('heading', { name: /People/ })).toBeVisible();
      await expect(page.getByText('Linked to Ana Ruiz · 94%')).toBeVisible();

      await expect(page).toHaveScreenshot(`graph-review-draft-${name}.png`);
    });
  }

  test('extracting @ phone-390', async ({ page }) => {
    await installNotesApi(page);
    await installGraphReviewApi(page, { state: 'extracting' });
    await page.setViewportSize(PHONE);
    await page.goto(harnessUrl({ route: '/notes/n1?review=1' }));
    await waitForInter(page);

    await expect(page.getByText('Reading your note and transcript…')).toBeVisible();
    // The progress bar animates; mask it so the baseline is stable.
    await expect(page).toHaveScreenshot('graph-review-extracting-phone-390.png', {
      mask: [page.getByRole('progressbar')],
    });
  });

  test('committed @ desktop-1440', async ({ page }) => {
    await installNotesApi(page);
    await installGraphReviewApi(page, { state: 'committed' });
    await page.setViewportSize(DESKTOP);
    await page.goto(harnessUrl({ route: '/notes/n1?review=1' }));
    await waitForInter(page);

    await expect(page.getByRole('button', { name: 'Revert…' })).toBeVisible();
    await expect(page.getByRole('heading', { name: /People/ })).toBeVisible();

    await expect(page).toHaveScreenshot('graph-review-committed-desktop-1440.png');
  });

  test('row editor @ phone-390', async ({ page }) => {
    await installNotesApi(page);
    await installGraphReviewApi(page);
    await page.setViewportSize(PHONE);
    await page.goto(harnessUrl({ route: '/notes/n1?review=1' }));
    await waitForInter(page);

    await expect(page.getByRole('heading', { name: /People/ })).toBeVisible();
    await page.getByRole('button', { name: 'More actions for Ana Ruiz', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Edit…' }).click();
    const dialog = page.getByRole('dialog', { name: 'Edit Ana Ruiz' });
    await expect(dialog).toBeVisible();
    await expect(dialog.getByRole('textbox', { name: 'Job title' })).toHaveValue('Staff engineer');

    await expect(page).toHaveScreenshot('graph-review-editor-phone-390.png');
  });
});
