import { expect, test } from '@playwright/test';
import { harnessUrl, waitForInter } from '../support/harness';
import { installGraphApi } from '../support/graphApi';

/**
 * Settings → Knowledge graph (`/settings/knowledge-graph`, issue #369, epic
 * #346): the extraction, resolution and domain preferences plus the attribute
 * browser, at desktop and phone width, and the add-attribute dialog — full
 * screen on a phone.
 *
 * Baselines are generated by CI's visual-baselines workflow (the pinned
 * Playwright image), never locally.
 */

const PHONE = { width: 390, height: 844 };
const DESKTOP = { width: 1440, height: 900 };

const WIDTHS = [
  ['phone-390', PHONE],
  ['desktop-1440', DESKTOP],
] as const;

test.describe('Knowledge graph settings', () => {
  for (const [name, viewport] of WIDTHS) {
    test(`knowledge graph settings @ ${name}`, async ({ page }) => {
      await installGraphApi(page);
      await page.setViewportSize(viewport);
      await page.goto(harnessUrl({ route: '/settings/knowledge-graph' }));
      await waitForInter(page);

      const main = page.locator('main');
      await expect(main.getByRole('heading', { name: 'Knowledge graph', level: 1 })).toBeVisible();
      // Waiting on the attribute browser's CONTENT, the last thing to load.
      await expect(main.getByText('Nickname', { exact: true })).toBeVisible();
      await expect(main.getByText('Industry', { exact: true })).toBeVisible();

      await expect(page).toHaveScreenshot(`graph-settings-${name}.png`, { fullPage: true });
    });

    test(`add attribute dialog @ ${name}`, async ({ page }) => {
      await installGraphApi(page);
      await page.setViewportSize(viewport);
      await page.goto(harnessUrl({ route: '/settings/knowledge-graph' }));
      await waitForInter(page);

      await expect(page.getByText('Nickname', { exact: true })).toBeVisible();
      await page.getByRole('button', { name: 'Add attribute' }).click();
      const dialog = page.getByRole('dialog', { name: 'Add attribute' });
      await expect(dialog).toBeVisible();

      await expect(page).toHaveScreenshot(`graph-settings-add-dialog-${name}.png`);
    });
  }

  test('connected knowledge turned off @ desktop-1440', async ({ page }) => {
    await installGraphApi(page, { graphDisabled: true });
    await page.setViewportSize(DESKTOP);
    await page.goto(harnessUrl({ route: '/settings/knowledge-graph' }));
    await waitForInter(page);

    await expect(
      page.getByText(/connected knowledge is turned off on this deployment/i),
    ).toBeVisible();
    await expect(page.getByText('Nickname', { exact: true })).toBeVisible();

    await expect(page).toHaveScreenshot('graph-settings-disabled-desktop-1440.png');
  });
});
