import { BadRequestException, ConflictException, Injectable, Logger } from '@nestjs/common';
import { Prisma, type NoteTemplate } from '@prisma/client';

import { PrismaService } from '../prisma/prisma.service';
import { NoteTemplateAccessService } from './access/note-template-access.service';
import { parseTemplateStructure } from './generation/prompt';
import {
  MAX_INSTRUCTIONS_CHARS,
  type CreateNoteTemplateDto,
  type ListNoteTemplatesQueryDto,
  type NoteOutputFormat,
  type NoteTemplateResponse,
  type UpdateNoteTemplateDto,
} from './dto/note-template.dto';

// =============================================================================
// NoteTemplatesService (issue #50, epic #45)
// =============================================================================
//
// The CRUD half of issue #50: list, read, create, edit, delete and duplicate.
// The preview half lives next door in `NoteTemplatePreviewService`, because it
// is a generation and shares nothing with these six but the access check.
//
// -----------------------------------------------------------------------------
// THREE THINGS IN HERE ARE POLICY, NOT PLUMBING
// -----------------------------------------------------------------------------
//
// 1. **A LIST IS THE UNION OF YOURS AND THE BUILT-INS** (spec §7.1). A
//    brand-new account with zero templates of its own still opens a full,
//    usable catalogue — that is the whole reason built-ins are seeded, and a
//    list scoped to `ownerId: userId` would quietly undo it.
//
// 2. **A DELETE THAT WOULD ORPHAN NOTHING DELETES; ANYTHING ELSE ARCHIVES.**
//    `notes.template_id` is `SetNull`, so a hard delete is *possible* even
//    after the template has produced notes — and that is exactly why the check
//    is here rather than left to the database: `SetNull` would silently strip
//    the provenance from every note generated by this template, and a note that
//    can no longer say what produced it is the opposite of what this epic is
//    for. Archiving keeps the row, keeps every referencing `templateId`, and
//    takes it out of the picker, which is what "delete" actually means to a
//    user whose notes still point at it.
//
// 3. **DUPLICATE COPIES EVERY COLUMN, NOT JUST `instructions`** (spec §7.3).
//    A "start from a variant" flow that dropped structure/tone/length on the
//    way in would hand the user a form they still have to refill from scratch —
//    the exact failure §4.3 rejects flattening those fields for in the first
//    place. `isArchived` resets to `false`: a duplicate is a fresh starting
//    point, never an archived one.
// =============================================================================

/** The `(owner_id, name)` constraint, as Prisma names it in a P2002. */
const NAME_UNIQUE_FIELDS = ['ownerId', 'name'];

@Injectable()
export class NoteTemplatesService {
  private readonly logger = new Logger(NoteTemplatesService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly access: NoteTemplateAccessService,
  ) {}

  // ---------------------------------------------------------------------------
  // Reads
  // ---------------------------------------------------------------------------

  /**
   * The caller's own templates PLUS every built-in, each flagged.
   *
   * ⚠ `OR: [{ ownerId: null }, { ownerId: userId }]` IS THE WHOLE ACCESS RULE
   * FOR THIS ROUTE, and it is expressed as a `where` rather than as a filter
   * applied to a wider read: a query that fetched everything and filtered in
   * JavaScript is one `return` away from publishing another user's prompts.
   *
   * `isArchived` narrows only when asked. Built-ins are never archived in
   * practice (nothing can write to them), so this flag is about the caller's
   * own rows.
   *
   * `includeHidden` (issue #310) narrows the same way, over the CALLER'S OWN
   * `user_hidden_note_templates` rows. The `hiddenBy` include is filtered to
   * `userId` too — another user having hidden a built-in must never make it
   * read as hidden here — so `hidden` is simply "did that filtered relation
   * come back non-empty".
   */
  async list(userId: string, query: ListNoteTemplatesQueryDto) {
    const where: Prisma.NoteTemplateWhereInput = {
      OR: [{ ownerId: null }, { ownerId: userId }],
      ...(query.includeArchived ? {} : { isArchived: false }),
      ...(query.includeHidden ? {} : { hiddenBy: { none: { userId } } }),
    };

    const rows = await this.prisma.noteTemplate.findMany({
      where,
      orderBy: [{ name: 'asc' }],
      include: { hiddenBy: { where: { userId }, select: { userId: true } } },
    });

    const items = rows.map((row) => toResponse(row, row.hiddenBy.length > 0));

    return { items, total: items.length };
  }

  /** One template — own or built-in. Anything else is a 404. */
  async get(userId: string, templateId: string): Promise<NoteTemplateResponse> {
    const { template } = await this.access.require(userId, templateId, 'read');

    return toResponse(template, await this.isHidden(userId, templateId));
  }

  // ---------------------------------------------------------------------------
  // Writes
  // ---------------------------------------------------------------------------

  /**
   * Create one, owned by the caller.
   *
   * ⚠ `ownerId: userId`, UNCONDITIONALLY. The DTO has no owner field (see its
   * header) and this line is the other half of that promise: there is no input,
   * from any role, that reaches this method and produces `ownerId: null`. A
   * client cannot ask for a built-in.
   */
  async create(userId: string, dto: CreateNoteTemplateDto): Promise<NoteTemplateResponse> {
    assertInstructionsFit(dto.instructions);

    try {
      const created = await this.prisma.noteTemplate.create({
        data: {
          ownerId: userId,
          name: dto.name,
          description: dto.description,
          instructions: dto.instructions,
          outputFormat: dto.outputFormat,
          structure: dto.structure,
          tone: dto.tone,
          length: dto.length,
          model: dto.model,
        },
      });

      // A row created a moment ago cannot have been hidden by anyone yet.
      return toResponse(created, false);
    } catch (error) {
      throw this.toNameConflict(error, dto.name);
    }
  }

  /**
   * Edit one of the caller's own.
   *
   * A built-in reaches `access.require(..., 'write')` and is refused there with
   * a 403; somebody else's reaches it and is refused with a 404. Neither
   * decision is repeated here — there is exactly one place in this module that
   * decides it.
   */
  async update(
    userId: string,
    templateId: string,
    dto: UpdateNoteTemplateDto,
  ): Promise<NoteTemplateResponse> {
    await this.access.require(userId, templateId, 'write');

    if (dto.instructions !== undefined) {
      assertInstructionsFit(dto.instructions);
    }

    // Only what was sent. An absent key means "leave it alone"; a `null` on the
    // three nullable columns means "clear it", which is a different statement
    // and one Prisma expresses directly.
    const data: Prisma.NoteTemplateUpdateInput = {};

    if (dto.name !== undefined) data.name = dto.name;
    if (dto.description !== undefined) data.description = dto.description;
    if (dto.instructions !== undefined) data.instructions = dto.instructions;
    if (dto.outputFormat !== undefined) data.outputFormat = dto.outputFormat;
    if (dto.structure !== undefined) data.structure = dto.structure;
    if (dto.tone !== undefined) data.tone = dto.tone;
    if (dto.length !== undefined) data.length = dto.length;
    if (dto.model !== undefined) data.model = dto.model;
    if (dto.isArchived !== undefined) data.isArchived = dto.isArchived;

    try {
      const updated = await this.prisma.noteTemplate.update({
        where: { id: templateId },
        data,
      });

      return toResponse(updated, await this.isHidden(userId, templateId));
    } catch (error) {
      throw this.toNameConflict(error, dto.name ?? '');
    }
  }

  /**
   * Delete one of the caller's own — or archive it when notes still name it.
   *
   * ⚠ THE COUNT IS OF `notes`, AND THE REFERENCING NOTE IS NEVER TOUCHED. Its
   * `templateId` survives archiving intact, which is the point: a note keeps
   * saying what produced it. See rule 2 in the header for why `SetNull` being
   * available is an argument FOR this check rather than against it.
   */
  async remove(userId: string, templateId: string) {
    await this.access.require(userId, templateId, 'write');

    const noteCount = await this.prisma.note.count({ where: { templateId } });

    if (noteCount > 0) {
      await this.prisma.noteTemplate.update({
        where: { id: templateId },
        data: { isArchived: true },
      });

      this.logger.log(
        `Template ${templateId} archived rather than deleted: ${noteCount} note(s) reference it`,
      );

      return { id: templateId, outcome: 'archived' as const, noteCount };
    }

    await this.prisma.noteTemplate.delete({ where: { id: templateId } });

    return { id: templateId, outcome: 'deleted' as const, noteCount: 0 };
  }

  /**
   * Copy any template the caller can READ into one they own.
   *
   * ⚠ THE ACCESS LEVEL IS `'read'`, NOT `'write'`, AND THAT IS THE FEATURE.
   * Duplicating a built-in is the sanctioned — and only — way to customise one
   * (§7.3); a `'write'` check here would 403 on precisely the row this endpoint
   * exists to serve. The write being authorised is the creation of the caller's
   * OWN new row, which needs no authority over the source at all.
   *
   * No `duplicated_from_id` is recorded, deliberately (§7.3): a template is a
   * recipe, not evidence. Once duplicated it is simply the user's own template.
   */
  async duplicate(userId: string, templateId: string): Promise<NoteTemplateResponse> {
    const { template } = await this.access.require(userId, templateId, 'read');

    const name = await this.uniqueCopyName(userId, template.name);

    const created = await this.prisma.noteTemplate.create({
      data: {
        ownerId: userId,
        name,
        description: template.description,
        instructions: template.instructions,
        outputFormat: template.outputFormat,
        structure: template.structure as Prisma.InputJsonValue,
        tone: template.tone,
        length: template.length,
        model: template.model,
        // A duplicate is a fresh, ACTIVE starting point — never an archived one
        // — even when the row it was copied from is archived (§7.3).
        isArchived: false,
      },
    });

    // A fresh copy is visible even when its source is hidden — duplicating
    // a template is an explicit ask to work with it.
    return toResponse(created, false);
  }

  // ---------------------------------------------------------------------------
  // Per-user visibility (issue #310)
  // ---------------------------------------------------------------------------

  /**
   * Hide a template from the caller's OWN picker. Idempotent.
   *
   * ⚠ THE ACCESS LEVEL IS `'read'`, NOT `'write'`, AND THAT IS THE FEATURE —
   * the same argument `duplicate` makes. Hiding writes one row in
   * `user_hidden_note_templates` keyed on the caller; nothing on the shared
   * `note_templates` row changes, so the built-in 403 (which exists to keep
   * that shared row immutable) has nothing to protect here. Built-ins are
   * precisely what most users will want to hide. Another user's template is
   * still a 404, because `'read'` already refuses it.
   *
   * An upsert with an empty `update`, so hiding twice is a no-op rather than a
   * P2002 — a double-clicked button must not produce an error.
   */
  async hide(userId: string, templateId: string): Promise<void> {
    const { builtIn } = await this.access.require(userId, templateId, 'read');

    await this.prisma.userHiddenNoteTemplate.upsert({
      where: { userId_templateId: { userId, templateId } },
      create: { userId, templateId },
      update: {},
    });

    await this.audit(userId, 'note_template:hide', templateId, { templateId, builtIn });
  }

  /**
   * Un-hide a template. Idempotent: un-hiding one that is not hidden succeeds.
   *
   * `deleteMany`, not `delete`, so an absent row is zero rows affected rather
   * than a P2025. The template itself must still be readable — an unreadable
   * id is the same 404 every other route answers.
   */
  async unhide(userId: string, templateId: string): Promise<void> {
    const { builtIn } = await this.access.require(userId, templateId, 'read');

    await this.prisma.userHiddenNoteTemplate.deleteMany({ where: { userId, templateId } });

    await this.audit(userId, 'note_template:unhide', templateId, { templateId, builtIn });
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /** Has THIS caller hidden this template? Never anybody else's answer. */
  private async isHidden(userId: string, templateId: string): Promise<boolean> {
    const row = await this.prisma.userHiddenNoteTemplate.findUnique({
      where: { userId_templateId: { userId, templateId } },
      select: { userId: true },
    });

    return row != null;
  }

  /**
   * One audit row, `targetType: 'note_template'` — the same shape
   * `NotesService.audit` writes for notes.
   */
  private async audit(
    userId: string,
    action: string,
    templateId: string,
    meta: Prisma.InputJsonObject,
  ): Promise<void> {
    await this.prisma.auditEvent.create({
      data: {
        actorUserId: userId,
        action,
        targetType: 'note_template',
        targetId: templateId,
        meta,
      },
    });
  }
  // ---------------------------------------------------------------------------

  /**
   * `"X (copy)"`, or `"X (copy 2)"`, … — the first that is free.
   *
   * `@@unique([ownerId, name])` is a real constraint and duplicating twice is
   * an ordinary thing to do, so the suffix is resolved rather than left to
   * collide. The names are read in ONE query and the gap is found in memory:
   * a loop of `findFirst`s would issue an unbounded number of round trips to
   * answer a question one `LIKE` already answers.
   *
   * This is a best-effort convenience, not a lock — two concurrent duplicates
   * of the same template can still race onto the same name, and the loser gets
   * the ordinary 409 from `create`. Serialising it would mean holding a lock
   * across a user-facing request to prevent a collision the user resolves by
   * pressing the button again.
   */
  private async uniqueCopyName(userId: string, sourceName: string): Promise<string> {
    const base = `${sourceName} (copy)`;

    const taken = new Set(
      (
        await this.prisma.noteTemplate.findMany({
          where: { ownerId: userId, name: { startsWith: base } },
          select: { name: true },
        })
      ).map((row) => row.name),
    );

    if (!taken.has(base)) return base;

    for (let n = 2; n < 1_000; n += 1) {
      const candidate = `${sourceName} (copy ${n})`;

      if (!taken.has(candidate)) return candidate;
    }

    // A user with a thousand copies of one template has other problems; the
    // constraint still protects the row, and `create` answers 409.
    return `${sourceName} (copy)`;
  }

  /**
   * Turn the `(owner_id, name)` collision into a 409 naming the name.
   *
   * ⚠ ANY OTHER P2002 IS RE-THROWN UNTOUCHED. Swallowing every unique-constraint
   * failure as "that name is taken" would report an unrelated database problem
   * as a user input error, which is how a real defect gets filed as user
   * confusion.
   */
  private toNameConflict(error: unknown, name: string): unknown {
    if (
      error instanceof Prisma.PrismaClientKnownRequestError &&
      error.code === 'P2002' &&
      mentionsNameConstraint(error)
    ) {
      return new ConflictException(
        `You already have a template called "${name}". Choose a different name.`,
      );
    }

    return error;
  }
}

/**
 * Refuse an oversized `instructions` body, NAMING BOTH NUMBERS.
 *
 * ⚠ NOT A ZOD RULE, AND `dto/note-template.dto.ts`'s header says why at length:
 * `nestjs-zod` renders every parse failure as a flat `"Validation failed"`, so
 * a `.max()` would take the size back out of the message. Issue #50 asks for
 * the size to be IN the message, so the ceiling is checked here, once, on every
 * path that can set the column — create, update, and a preview's inline body.
 */
export function assertInstructionsFit(instructions: string): void {
  if (instructions.length <= MAX_INSTRUCTIONS_CHARS) return;

  throw new BadRequestException(
    `These instructions are ${instructions.length.toLocaleString('en-US')} characters; a template ` +
      `allows at most ${MAX_INSTRUCTIONS_CHARS.toLocaleString('en-US')}. Shorten the prompt, or ` +
      'move the detail into the structure list.',
  );
}

/** Does this P2002 name the `(owner_id, name)` constraint? */
function mentionsNameConstraint(error: Prisma.PrismaClientKnownRequestError): boolean {
  const meta = (error.meta ?? {}) as Record<string, unknown>;
  const target = meta.target;

  if (Array.isArray(target)) {
    return target.some((field) => NAME_UNIQUE_FIELDS.includes(String(field)));
  }

  if (typeof target === 'string') {
    return NAME_UNIQUE_FIELDS.some((field) => target.includes(field)) || target.includes('name');
  }

  // The driver adapter reports the constraint under a different shape; when
  // neither is readable, treat a P2002 on this table as the name collision —
  // `note_templates` has exactly one unique constraint, so there is nothing
  // else it could be.
  return true;
}

/**
 * One row as the wire sees it.
 *
 * `hidden` is an ARGUMENT, not a column: it is a fact about the caller, not
 * the row (issue #310), so every caller of this function states it.
 *
 * ⚠ `builtIn` IS DERIVED HERE AND `ownerId` IS DROPPED HERE. There is no
 * `is_built_in` column (spec §4.3) and there is no second statement of the fact
 * on the wire either — one boolean, computed in one place, that cannot disagree
 * with the row it came from.
 *
 * `structure` goes out through `parseTemplateStructure`, the SAME total reader
 * `assemblePrompt` uses: what the editor loads back is then exactly what the
 * prompt will contain, down to the entries a malformed JSONB blob would drop.
 * A second, more permissive projection here would show a user a section the
 * generation silently omits.
 */
export function toResponse(template: NoteTemplate, hidden: boolean): NoteTemplateResponse {
  return {
    id: template.id,
    name: template.name,
    description: template.description,
    instructions: template.instructions,
    outputFormat: template.outputFormat as NoteOutputFormat,
    structure: parseTemplateStructure(template.structure),
    tone: template.tone,
    length: template.length,
    model: template.model,
    isArchived: template.isArchived,
    builtIn: template.ownerId === null,
    // Per-caller, so it cannot be read off the row — the caller supplies it.
    hidden,
    // ISO strings, matching the published schema — see its note on why these
    // are not `z.date()`.
    createdAt: template.createdAt.toISOString(),
    updatedAt: template.updatedAt.toISOString(),
  };
}
